"""Writes agent outputs to local files for review."""
from pathlib import Path
from datetime import datetime
import json
from backend.db.schemas import PatternMatch, AuditResponse, MetricsInput
from backend.config import OUTPUT_PATH


def _timestamp() -> str:
    return datetime.now().strftime("%Y-%m-%d_%H%M%S")


def write_alert(match: PatternMatch, metrics: MetricsInput) -> str:
    ts = _timestamp()
    filename = f"alert_{ts}_{match.pattern_id}.md"
    path = OUTPUT_PATH / filename

    survival_pct = int(match.survival_rate * 100)
    failure_pct = 100 - survival_pct
    total = match.failure_count + match.survival_count

    signals_md = "\n".join(
        f"| {s.signal} | {s.status} | "
        f"{'~' + str(s.days_detectable) + ' days ago' if s.days_detectable else 'Just emerged'} |"
        for s in match.warning_signals_detected
    ) or "| No specific signals detected yet | — | — |"

    playbook_md = "\n".join(
        f"{i+1}. **{step.split(' — ')[0]}**"
        + (f" — {step.split(' — ')[1]}" if " — " in step else "")
        for i, step in enumerate(match.survival_playbook)
    )

    failures_md = "\n".join(
        f"| {f['company']} | {'❌ Failed' if f['outcome'] == 'Failed' else '⚠️ ' + f['outcome']} "
        f"| {f['detail']} |"
        for f in match.famous_failures
    )

    content = f"""# ⚠️ FAILURE PATTERN DETECTED
**Pattern:** {match.pattern_name} ({match.pattern_id})
**Confidence:** {int(match.confidence * 100)}%
**Startup:** {metrics.startup_name} | Month {metrics.current_month}
**Detected:** {datetime.now().strftime("%B %d, %Y at %H:%M")}

---

## What This Pattern Means
{match.narrative}

---

## Warning Signals Present In Your Data

| Signal | Status | When First Detectable |
|--------|--------|-----------------------|
{signals_md}

---

## Your Metrics vs. Pattern Trigger

| Metric | Your Value | Risk |
|--------|-----------|------|
| Monthly MRR growth | {metrics.mrr_growth_rate*100:.1f}% | {'⚠️' if metrics.mrr_growth_rate < 0.15 else '✅'} |
| Monthly churn rate | {metrics.churn_rate*100:.1f}% | {'⚠️' if metrics.churn_rate > 0.07 else '✅'} |
| NPS | {metrics.nps} | {'⚠️' if metrics.nps < 45 else '✅'} |
| Runway | {metrics.runway_months} months | {'🔴' if metrics.runway_months < 9 else '⚠️' if metrics.runway_months < 15 else '✅'} |
| Headcount | {metrics.headcount} | — |

---

## Historical Outcomes

Of **{total:,} startups** that matched this exact pattern:
- ❌ **{failure_pct}% failed** within {match.days_to_crisis} days
- ✅ **{survival_pct}% survived** ({match.survival_count} companies)

**Estimated time to crisis if no action taken: ~{match.days_to_crisis} days**

---

## Survival Playbook
*Used by all {match.survival_count} companies that survived this pattern*

{playbook_md}

---

## Companies That Matched This Pattern

| Company | Outcome | What Happened |
|---------|---------|---------------|
{failures_md}

---

## Your Action Checklist This Week

- [ ] **Today:** Review this report with your co-founder/board
- [ ] **48 hours:** Verify the warning signals in your own data
- [ ] **This week:** Begin step 1 of the survival playbook
- [ ] **30 days:** Re-run pattern analysis to measure progress

---

*Generated by The Failure Oracle*
*Pattern library: 15 documented patterns | {total:,} historical cases*
*File: {path}*
"""

    path.write_text(content, encoding="utf-8")

    # Always keep a "latest" copy for quick access
    (OUTPUT_PATH / "latest_alert.md").write_text(content, encoding="utf-8")

    # JSON version
    json_path = OUTPUT_PATH / f"alert_{ts}_{match.pattern_id}.json"
    json_path.write_text(
        json.dumps(
            {
                "pattern_id": match.pattern_id,
                "pattern_name": match.pattern_name,
                "confidence": match.confidence,
                "days_to_crisis": match.days_to_crisis,
                "survival_rate": match.survival_rate,
                "playbook": match.survival_playbook,
                "metrics": metrics.model_dump(),
                "generated_at": datetime.now().isoformat(),
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    (OUTPUT_PATH / "latest_alert.json").write_text(
        json_path.read_text(encoding="utf-8"), encoding="utf-8"
    )

    return str(path)


def write_audit(audit: AuditResponse) -> str:
    ts = _timestamp()
    filename = f"audit_{ts}.md"
    path = OUTPUT_PATH / filename

    risk_emoji = {"LOW": "🟢", "MEDIUM": "🟡", "HIGH": "🔴", "CRITICAL": "💀"}.get(
        audit.risk_level, "⚠️"
    )

    content = f"""# 📋 DECISION AUDIT
**Decision:** {audit.decision}
**Risk Level:** {risk_emoji} {audit.risk_level}
**Audited:** {datetime.now().strftime("%B %d, %Y at %H:%M")}

---

## Historical Case Analysis

| Outcome | Count |
|---------|-------|
| ✅ Success | {audit.success_cases} |
| ❌ Failure | {audit.failure_cases} |
| **Total** | **{audit.total_cases}** |

## Key Differentiator
> *{audit.key_differentiator}*

## Recommendation
{audit.recommendation}

---

*Generated by The Failure Oracle*
*File: {path}*
"""

    path.write_text(content, encoding="utf-8")
    (OUTPUT_PATH / "latest_audit.md").write_text(content, encoding="utf-8")
    return str(path)
